AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:

  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: date
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  Quote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: quote.handler
      Runtime: python2.7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: QuotesTable
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /quote/{quoteId}
            Method: get
        PutEvent:
          Type: Api
          Properties:
            Path: /quote
            Method: put
  
  QuotePage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: quotepage.handler
      Runtime: python2.7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: QuotesTable
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /quotes/{page}
            Method: get