link rel: 'stylesheet', href: '/styles/material.min.css'
link rel: 'script', href: '/script/material.js'
link rel: 'stylesheet', href: 'https://fonts.googleapis.com/icon?family=Material+Icons'
link rel: 'stylesheet', href: '/styles/main.css'
link rel: 'stylesheet', href: '/styles/dialog-polyfill.css'